# Generated by Django 5.1.7 on 2025-03-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_lesson_image_alter_lesson_video_http_url'),
        ('users', '0002_alter_user_options_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма платежа')),
                ('payment_system', models.CharField(choices=[('Наличные', 'Наличные'), ('Перевод на счет', 'Перевод на счет')], max_length=100, verbose_name='Способ оплаты')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauments', to='lms.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
