# Generated by Django 5.1.7 on 2025-03-15 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_lesson_image_alter_lesson_video_http_url'),
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата платежа'),
        ),
    ]
