# Generated by Django 5.1.7 on 2025-04-03 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_coursesubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubscription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='lms.course', verbose_name='Курс'),
        ),
    ]
